language: go

go:
  - 1.20.x

services:
  - docker

env:
  HOST=0.0.0.0
  PORT=8080

script:
  - make test
  - make build-docker

deploy:
    provider: script
    script: make docker-push
    on:
        branch: master
